### ISSUE TITLE
Add simple email support for Alerting

### ISSUE THREAD

**Issue by CarlMeadows** [opendistro-for-elasticsearch/alerting#3]
Provide a pre-built destination type for email in Alerting to make it easy to send notifications without using a webhook.

**Comment by arnabdutta** [comment]
Any updates on this ?

**Comment by sivachandran21** [comment]
Team any update on this requirement

**Comment by elfisher** [comment]
Hi @sivachandran21 we have not started working on this.

**Comment by Angrboda2** [comment]
Does labeling it backlog indicate a commitment to get it done in a reasonable time-frame or is it in the ice box? While we could write a webhook endpoint to send emails this is currently a major roadblock to adoption.

**Comment by kris4ever** [comment]
I agree that this is a major feature that would help changing to OpenDistro.

**Comment by burandobata** [comment]
+1

**Comment by YanekR** [comment]
+1

**Comment by YanekR** [comment]
+1

**Comment by autorun1918** [comment]
+1

**Comment by nean-and-i** [comment]
+1

**Comment by ash74268** [comment]
I think this a pressing item for everyone.  is there a timeline that we can expect ?

**Comment by elfisher** [comment]
Hi @ash74268 we have not started working on this yet, but we do welcome contributions from the community so if someone is interested in contributing please reach out.

**Comment by jadams5** [comment]
Chiming in that this is a blocker for our adoption as well.  We went down the path of standing up a POC of this stack based on the screenshot showing SMTP support, but we hit a wall when trying to configure it.

**Comment by artar94** [comment]
I see that @dchauviere has already implemented SMTP support https://github.com/dchauviere/alerting/commit/42ff1eb86c17d343c64755a69b2b4aa0469bbcbc . Is it possible to somehow coordinate the creation of pull request in the main project?

**Comment by fbaligand** [comment]
Thanks @dchauviere for your PRs!

Can't wait that these PRs are merged and released!

**Comment by dchauviere** [comment]
Not a real developer,  review may be long ... 😄

**Comment by gulywwx** [comment]
Is there any update for that. I am looking for a similar SMTP feature.

**Comment by psyapathy** [comment]
+1!

**Comment by vahidnia** [comment]
any update?

**Comment by bkraegelin** [comment]
+1
email is our no. 1 way to alerting in all our systems

**Comment by xiangweilee** [comment]
this is a must-have feature

**Comment by EBCEEB** [comment]
FYI While waiting, I'm using prometheus' alertmanager via custom webhook. The only inconvenient thing is message body in JSON.

**Comment by g3rhard** [comment]
> FYI While waiting, I'm using prometheus' alertmanager via custom webhook. The only inconvenient thing is message body in JSON.

Can you send any details about it?

**Comment by EBCEEB** [comment]
> > FYI While waiting, I'm using prometheus' alertmanager via custom webhook. The only inconvenient thing is message body in JSON.
> 
> Can you send any details about it?

Alerting -> Destinations:
  Type: Custom webhook
  Define endpoint by URL: http://<host>:9093/api/v1/alerts

Monitors -> Triggers -> Actions:
  Destination: <Defined above>
  Message:
[{
        "annotations": {
            "description": "{{ctx.results.0.hits.hits.0._source.message}}",
            "summary": "...."
        },
        "labels": {
            "alertname": "{{ctx.trigger.name}}",
            "severity": "...",
            "source": "elasticsearch"
        },
        "status": "firing"
    }]

**Comment by nc-guek** [comment]
+1

**Comment by dgsus** [comment]
+1

**Comment by ksyblast** [comment]
+1

**Comment by jomeier** [comment]
+1

**Comment by masayyed** [comment]
+1

**Comment by charithra7** [comment]
Hi,

Any update regarding this request ??

This is a key feature that must be available.

**Comment by rastorehak** [comment]
I would like to see this feature too.

**Comment by parabinda** [comment]
Opendistro is a great effort by Amazon Inc.
However without an Alerting destination like e-mail, Alerting will be highly restricted.
Please add this feature asap.
Or provide an alternative

**Comment by lacksfish** [comment]
Email would be highly important, how is this feature still missing?
Standard Kibana already offers this feature, why would the wheel be reinvented here?

https://www.elastic.co/guide/en/kibana/current/defining-alerts.html#defining-alerts-actions-details

**Comment by yxz900** [comment]
> > > FYI While waiting, I'm using prometheus' alertmanager via custom webhook. The only inconvenient thing is message body in JSON.
> > 
> > 
> > Can you send any details about it?
> 
> Alerting -> Destinations:
> Type: Custom webhook
> Define endpoint by URL: http://--host--:9093/api/v1/alerts
> 
> Monitors -> Triggers -> Actions:
> Destination: --Defined above--
> Message:
> [{
> "annotations": {
> "description": "{{ctx.results.0.hits.hits.0._source.message}}",
> "summary": "...."
> },
> "labels": {
> "alertname": "{{ctx.trigger.name}}",
> "severity": "...",
> "source": "elasticsearch"
> },
> "status": "firing"
> }]
Can you provide details on how to configure alertmanager to send out emails using the webhook? Thanks:-)

**Comment by youtous** [comment]
I'm using https://github.com/youtous/odfe-alerts-handler

**Comment by nerddelphi** [comment]
@lacksfish Email notification is licensed feature ($$).
![image](https://user-images.githubusercontent.com/28447854/88067578-8c955400-cb45-11ea-8fdd-03516e38f140.png)

**Comment by fbaligand** [comment]
Well, like webhooks, that are supported by open distro alerting since first version.

**Comment by EBCEEB** [comment]
>  Can you provide details on how to configure alertmanager to send out emails using the webhook? Thanks:-)

Sorry, I have no config from a real system. I was using Ansible to configure Alertmanager.

Here is snippet from Ansible playbook:

```yaml
  global:
    resolve_timeout: 5m
    smtp_smarthost: '{{ smtp_host | default("mail:25") }}'
    auth_username: '{{ smtp_user }}'
    auth_password: '{{ smtp_pass }}'
    smtp_hello: '{{ ansible_fqdn }}'
    smtp_from: '{{ smtp_from | default(smtp_user | default("monitoring@" ~ dns_domain)) }}'
  route:
    receiver: email-default
    group_by:
    - alertname
    - instance
    group_wait: 30s
    group_interval: 1m
    repeat_interval: 1h
    routes:
    - receiver: email-elk
      match:
        source: elasticsearch
  receivers:
  - name: email-default
...
  - name: email-elk
    email_configs:
    - send_resolved: no
      to: '{{ alertmanager_email_dest }}'
      tls_config:
        insecure_skip_verify: yes
      headers:
        From: Event monitoring <{{ smtp_from | default(smtp_user | default("monitoring@" ~ dns_domain)) }}>
        Reply-To: devops@{{ dns_domain }}
        X-Alert-Source: elasticsearch
        X-Alert-Environment: '{{ env | default("unknown") }}'
```

Important things are:

- `global.resolve_timeout` must be set to some adequate value
- `global.smtp_*` and `global.auth_*` should be set for yours SMTP-server
- `route.routes` should contain a rule that routes messages from Elasticsearch (`match.source: elasticsearch` matches a label in alert definition (see example JSON)
- email config (`email-elk`) should have `send_resolved: no`
