### ISSUE TITLE
[BUG] Not able to create monitor and destination after 1.11.0 upgrade

### ISSUE THREAD

**Issue by ZhiXingHeYiApple** [opendistro-for-elasticsearch/alerting#303]
**Describe the bug**
We are not able to create new monitors and destination after upgrading from 1.10.2 to 1.11.0. If config SSL with X.509 PEM certificates, we face the same bug like #292, but if config SSL with Keystore and truststore files, we have to add configuration `opendistro_security.ssl.http.keystore_keypassword`(I don't know what is difference between `opendistro_security.ssl.http.keystore_keypassword` and `opendistro_security.ssl.http.keystore_password`) in `elasticsearch.yml` file to start es successfully when upgrading from 1.10.2 to 1.11.0. Although other plugin like `dev tool` `security` and so on can work normally, but alerting plugin can not create new monitor or destination, getting the exception: [alerting_exception] PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Other plugins installed**
The full Open Distro package (docker compose install)

**To Reproduce**
1. Go to 'Kibana -> Alerting -> Monitors'
2. Click on 'Create monitor'
3. Enter details for monitor (name, condition, schedule, etc.)
4. Click 'Create' to create the new montior
5. See error
Remark: the same as destination creation.

**Expected behavior**
New monitor or new destination to be getting created without error.

**Screenshots**

**Docker compose file content**
```
version: '3.3'
services:
  es7-node1:
    image: swr.cn-east-3.myhuaweicloud.com/bestsign-prod/bestsign-for-elasticsearch:1.11.0
    container_name: es7-node1
    environment:
      - cluster.name=es7-cluster
      - node.name=es7-node1
      - discovery.seed_hosts=es7-node1,es7-node2
      - cluster.initial_master_nodes=es7-node1,es7-node2
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - ES_BOOTSTRAP_MEMORY_LOCK=false
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - network.host=0.0.0.0 # required if not using the demo Security configuration
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - type: volume
        source: es7-data1
        target: /usr/share/elasticsearch/data
      - ./es7config/es-node.p12:/usr/share/elasticsearch/config/es-node.p12
      - ./es7config/truststore.jks:/usr/share/elasticsearch/config/truststore.jks
      - ./es7config/distro-admin.crt.pem:/usr/share/elasticsearch/config/distro-admin.crt.pem
      - ./es7config/distro-admin.key.pem:/usr/share/elasticsearch/config/distro-admin.key.pem
      - ./es7config/distro-admin-keystore.jks:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/distro-admin-keystore.jks
      - ./es7config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./es7config/internal_users.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/internal_users.yml
      - ./es7config/config.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/config.yml
    ports:
      - 9210:9200
      - 9610:9600 # required for Performance Analyzer
    networks:
      - es7-net
  es7-node2:
    image: swr.cn-east-3.myhuaweicloud.com/bestsign-prod/bestsign-for-elasticsearch:1.11.0
    container_name: es7-node2
    environment:
      - cluster.name=es7-cluster
      - node.name=es7-node2
      - discovery.seed_hosts=es7-node1,es7-node2
      - cluster.initial_master_nodes=es7-node1,es7-node2
      - bootstrap.memory_lock=true
      - ES_BOOTSTRAP_MEMORY_LOCK=false
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      #- discovery.zen.ping.unicast.hosts=es7-node1
      - network.host=0.0.0.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - type: volume
        source: es7-data2
        target: /usr/share/elasticsearch/data
      - ./es7config/es-node.p12:/usr/share/elasticsearch/config/es-node.p12
      - ./es7config/truststore.jks:/usr/share/elasticsearch/config/truststore.jks
      - ./es7config/distro-admin.crt.pem:/usr/share/elasticsearch/config/distro-admin.crt.pem
      - ./es7config/distro-admin.key.pem:/usr/share/elasticsearch/config/distro-admin.key.pem
      - ./es7config/distro-admin-keystore.jks:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/distro-admin-keystore.jks
      - ./es7config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./es7config/internal_users.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/internal_users.yml
      - ./es7config/config.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/config.yml
    
    ports:
      - 9211:9200
      - 9611:9600 # required for Performance Analyzer
    networks:
      - es7-net
  es7-kibana:
    image: amazon/opendistro-for-elasticsearch-kibana:1.11.0
    container_name: es7-kibana
    ports:
      - 5602:5601
    #expose:
     # - "5601"
    environment:
      ELASTICSEARCH_URL: https://es7-node1:9200
      ELASTICSEARCH_HOSTS: https://es7-node1:9200
    volumes:
      - ./es7config/es7-custom-kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - es7-net

volumes:
  es7-data1:
    driver: local
    driver_opts:
        type: none
        o: bind
        device: /data/es742/data1
  es7-data2:
    driver: local
    driver_opts:
        type: none
        o: bind
        device: /data/es742/data2
networks:
  es7-net:
```

**elasticsearch.yml**
```
cluster.name: "docker-cluster"
network.host: 0.0.0.0



opendistro_security.ssl.transport.keystore_type: PKCS12
opendistro_security.ssl.transport.keystore_filepath: es-node.p12
opendistro_security.ssl.transport.keystore_password: 222222233
opendistro_security.ssl.transport.truststore_type: JKS
opendistro_security.ssl.transport.truststore_filepath: truststore.jks
opendistro_security.ssl.transport.truststore_password: 999999999
opendistro_security.ssl.transport.enable_openssl_if_available: true
opendistro_security.ssl.transport.enforce_hostname_verification: false


opendistro_security.ssl.http.enabled: true
opendistro_security.ssl.http.keystore_type: PKCS12
opendistro_security.ssl.http.keystore_filepath: es-node.p12
opendistro_security.ssl.http.keystore_password: 222222233
opendistro_security.ssl.http.keystore_keypassword: 222222233
opendistro_security.ssl.http.truststore_type: JKS
opendistro_security.ssl.http.truststore_filepath: truststore.jks
opendistro_security.ssl.http.truststore_password: 999999999
opendistro_security.ssl.http.enable_openssl_if_available: true

opendistro_security.allow_unsafe_democertificates: true
opendistro_security.allow_default_init_securityindex: true

opendistro_security.nodes_dn:
  - CN=*.bestsign.dev, OU=SSL, O=Test, L=Test, C=CN
opendistro_security.authcz.admin_dn:
  - CN=distro-admin,OU=client,O=client,L=Test, C=CN

opendistro_security.audit.type: internal_elasticsearch
opendistro_security.enable_snapshot_restore_privilege: true
opendistro_security.check_snapshot_restore_write_privileges: true
opendistro_security.restapi.roles_enabled: ["all_access", "security_rest_api_access"]
cluster.routing.allocation.disk.threshold_enabled: false
node.max_local_storage_nodes: 3
```

**ElasticSearch Log**
```
es7-node1     | [2020-11-23T05:23:01,195][ERROR][c.a.o.a.u.AlertingException] [es7-node1] Alerting error: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
es7-node1     | [2020-11-23T05:23:01,196][WARN ][r.suppressed             ] [es7-node1] path: /_opendistro/_alerting/monitors, params: {refresh=wait_for}
es7-node1     | com.amazon.opendistroforelasticsearch.alerting.util.AlertingException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
es7-node1     |         at com.amazon.opendistroforelasticsearch.alerting.util.AlertingException$Companion.wrap(AlertingException.kt:80) ~[opendistro_alerting-1.11.0.1.jar:1.11.0.1]
es7-node1     |         at com.amazon.opendistroforelasticsearch.alerting.transport.TransportIndexMonitorAction$IndexMonitorHandler$resolveUserAndStart$1.onFailure(TransportIndexMonitorAction.kt:196) [opendistro_alerting-1.11.0.1.jar:1.11.0.1]
es7-node1     |         at org.elasticsearch.client.RestClient$FailureTrackingResponseListener.onDefinitiveFailure(RestClient.java:617) [elasticsearch-rest-client-7.9.1.jar:7.9.1]
es7-node1     |         at org.elasticsearch.client.RestClient$1.failed(RestClient.java:375) [elasticsearch-rest-client-7.9.1.jar:7.9.1]
es7-node1     |         at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:137) [httpcore-4.4.12.jar:4.4.12]
es7-node1     |         at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.executionFailed(DefaultClientExchangeHandlerImpl.java:101) [httpasyncclient-4.1.4.jar:4.1.4]
es7-node1     |         at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.failed(AbstractClientExchangeHandler.java:426) [httpasyncclient-4.1.4.jar:4.1.4]
es7-node1     |         at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.exception(HttpAsyncRequestExecutor.java:163) [httpcore-nio-4.4.12.jar:4.4.12]
es7-node1     |         at org.apache.http.impl.nio.client.InternalIODispatch.onException(InternalIODispatch.java:76) [httpasyncclient-4.1.4.jar:4.1.4]
es7-node1     |         at org.apache.http.impl.nio.client.InternalIODispatch.onException(InternalIODispatch.java:39) [httpasyncclient-4.1.4.jar:4.1.4]
es7-node1     |         at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:125) [httpcore-nio-4.4.12.jar:4.4.12]
es7-node1     |         at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162) [httpcore-nio-4.4.12.jar:4.4.12]
es7-node1     |         at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337) [httpcore-nio-4.4.12.jar:4.4.12]
es7-node1     |         at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315) [httpcore-nio-4.4.12.jar:4.4.12]
es7-node1     |         at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276) [httpcore-nio-4.4.12.jar:4.4.12]
es7-node1     |         at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) [httpcore-nio-4.4.12.jar:4.4.12]
es7-node1     |         at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591) [httpcore-nio-4.4.12.jar:4.4.12]
es7-node1     |         at java.lang.Thread.run(Thread.java:832) [?:?]
es7-node1     | Caused by: java.lang.Exception: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
es7-node1     |         ... 18 more
```
